version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/argocd/jenkins/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins1
  agent1:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent1
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDID+QaduUCazQBxfPEvtzUFuidov5i8rK2h29F2BIA2gbVQ2ygeYtPnKUBHe+8x7Trk3NWH7jqK8IQAtBbWx5DsHXQjwfi7kfXo5YrD7LqxyB8zqkMng+UdRcDDus02TFQNNf0lUR>
    networks:
      - jenkins1
networks:
  jenkins1:
    driver: bridge
