apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-deployment
  namespace: das
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap-server
          image: harbor.actia.local/test/ldap:v1
          ports:
            - containerPort: 389
          volumeMounts:
          - name: ldap-data
            mountPath: /var/lib/ldap
      volumes:
      - name: ldap-data
        persistentVolumeClaim:
          claimName: ldap-pvc