apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: harbor.actia.local/test/ldap:v1
          image: ldap:v33
          ports:
            - containerPort: 389