apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-data-pv
  namespace: das
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/lib/ldap