apiVersion: v1
kind: Service
metadata:
  name: ldap-service-external
  namespace: das
spec:
  selector:
    app: ldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
      nodePort: 30389
  type: NodePort